services:
  client:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./tmp/dist/:/usr/share/nginx/html
      - ./tmp/nginx.conf:/etc/nginx/conf.d/nginx.conf
    restart: unless-stopped
