name: CD

on:
  push:
    branches: dev

  pull_request:
    branches:
      - '*'

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build:production

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-action.pem
          chmod 600 ~/.ssh/github-action.pem
          cat >>~/.ssh/config <<EOF
          Host server
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/github-action.pem
            StrictHostKeyChecking no
          EOF

      - name: Push docker compose to remote host
        run: rsync -e ssh ./docker-compose.yml server:~/
        
      - name: Push dist folder
        run: rsync -a -e ssh ./dist server:~/

      - name: Build the stack
        run: ssh server 'sudo docker-compose pull; sudo docker-compose up -d --remove-orphans; sudo docker image prune -f'
